name: OneCompany
main: OneCompany\OneCompany
version: "1.0"
author: LightBlue
api:
- 1.12.0
- 1.13.0
- 2.0.0

permissions:
 Company.command.allow:
  description: "company command permission"
  default: ture
